[package]
name = "thrift"
description = "Rust bindings for the Apache Thrift RPC system"
edition = "2024"
version = "0.24.0"
license = "Apache-2.0"
authors = ["Apache Thrift Developers <dev@thrift.apache.org>"]
homepage = "http://thrift.apache.org"
documentation = "https://docs.rs/thrift"
repository = "https://github.com/apache/thrift/tree/master/lib/rs"
readme = "README.md"
exclude = ["Makefile*", "test/**", "*.iml"]
keywords = ["thrift"]

[dependencies]
byteorder = "1.5"
integer-encoding = "4"
uuid = "1"
log = { version = "0.4", optional = true }
ordered-float = { version = "5", features = ["serde"] }
threadpool = { version = "1.7", optional = true }

[features]
default = ["server"]
server = ["threadpool", "log"]

[dev-dependencies]
criterion = "0.7.0"
uuid = { version = "*", features = ["v4"] }

[[bench]]
name = "binary_protocol"
harness = false
